### ISSUE TITLE
Running Predictor

### ISSUE THREAD

**Issue by KittyDreadful** [davide97l/running-performance-calculator#1]
Hi,

I'm doing a Ragnar Relay next week and I'm trying to use your code for my team. Problem is - I don't know how to code :)  Do you have any interest in helping me set up a page to help my team predict our finish times?  

Thanks in advance.

**Comment by davide97l** [comment]
Hello @KittyDreadful, the website of this application is available here: https://davide97l-running-performance-calculator-streamlit-app-a6aedk.streamlitapp.com/. You can just input the required information and it shows your predicted time, let me know if you have trouble using it.
